name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0


      - name: 创建数据目录
        run: |
          mkdir -p _data
      - name: 生成文件列表
        run: |
          find . -type f -print > _data/file_list.txt
      - name: Update submodules
        run: |
          git submodule update --init --recursive

